import type { Metadata } from "next";
import {Boldonse } from "next/font/google";
import "./globals.css";
import Indexlayout from "@/components/layout";
import "@/../public/assets/css/plugins.css"
import "@/../public/assets/css/style.css"
import Scripts from "@/components/layout/scripts";
import Heade from "@/components/layout/heade";


const boldonse=Boldonse({
  variable:"--font-Boldonse",
  weight:"400",
  subsets:["latin"]
})

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Heade/>
      <body
      id="body"
        className={`gridAnim ${boldonse.className} creative-agency lines creative-agency loaded lines tt-transition tt-noise tt-magic-cursor tt-smooth-scroll antialiased`}
      >
        <Indexlayout>{children}</Indexlayout>
        <Scripts/>
      </body>
    </html>
  );
}
